#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Styling, testing and building yout project before commiting'


# Check tsconfig strandards
npm run check-types || 
(
    echo
    'Failed Type check.
     Are you seriously trying to write that ? Make the changes required above.'
    false;
)

# Check Prettier strandards
npm run check-format || 
(
    echo
    'Your styling looks disgusting. Prettier check failed. Run npm run format, add changes and try to commit again'
    false;
)

# Check ESLint strandard
npm run check-lint || 
(
    echo
    'ESLint check failed. Make the required changes listed above, add changes and try to commit again'
    false;
)

# If everithing is ok 

echo "Looks good to me .. Trying to build now.."\

npm run build || 
(
    echo ' Better call Bob.. Because your build failed. Next build failed : View the errors above to see why.'
)

echo 'You win this time.. I am commiting this now.. but be aware..'
